[2022-12-15T07:47:51.485+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2022-12-15T07:47:51.493+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2022-12-15T07:47:51.494+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T07:47:51.495+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-15T07:47:51.496+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-15T07:47:51.507+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_history_table> on 2022-12-14 00:00:00+00:00
[2022-12-15T07:47:51.514+0000] {standard_task_runner.py:55} INFO - Started process 1205 to run task
[2022-12-15T07:47:51.519+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_dag', 'create_history_table', 'scheduled__2022-12-14T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpov3adqp_']
[2022-12-15T07:47:51.521+0000] {standard_task_runner.py:83} INFO - Job 160: Subtask create_history_table
[2022-12-15T07:47:51.590+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [running]> on host b92abc15fbab
[2022-12-15T07:47:51.634+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_dag
AIRFLOW_CTX_TASK_ID=create_history_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-14T00:00:00+00:00
[2022-12-15T07:47:51.636+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);
[2022-12-15T07:47:51.642+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-15T07:47:51.767+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-15T07:47:51.771+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);, parameters: None
[2022-12-15T07:47:51.778+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=daily_spotify_dag, task_id=create_history_table, execution_date=20221214T000000, start_date=20221215T074751, end_date=20221215T074751
[2022-12-15T07:47:51.812+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-15T07:47:51.830+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-16T01:51:09.892+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2022-12-16T01:51:09.923+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2022-12-16T01:51:09.926+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:51:09.928+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-16T01:51:09.929+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:51:09.947+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_history_table> on 2022-12-14 00:00:00+00:00
[2022-12-16T01:51:09.957+0000] {standard_task_runner.py:55} INFO - Started process 354 to run task
[2022-12-16T01:51:09.962+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_dag', 'create_history_table', 'scheduled__2022-12-14T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmp_3okpyci']
[2022-12-16T01:51:09.970+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_history_table
[2022-12-16T01:51:10.249+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-14T00:00:00+00:00 [running]> on host 158c8f40aaa8
[2022-12-16T01:51:10.548+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_dag
AIRFLOW_CTX_TASK_ID=create_history_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-14T00:00:00+00:00
[2022-12-16T01:51:10.571+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);
[2022-12-16T01:51:10.639+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-16T01:51:13.941+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-16T01:51:13.947+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);, parameters: None
[2022-12-16T01:51:13.961+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "users" does not exist

[2022-12-16T01:51:13.982+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=daily_spotify_dag, task_id=create_history_table, execution_date=20221214T000000, start_date=20221216T015109, end_date=20221216T015113
[2022-12-16T01:51:14.050+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_history_table (relation "users" does not exist
; 354)
[2022-12-16T01:51:14.246+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T01:51:14.328+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
