[2022-12-16T01:51:12.273+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-15T00:00:00+00:00 [queued]>
[2022-12-16T01:51:12.346+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-15T00:00:00+00:00 [queued]>
[2022-12-16T01:51:12.353+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:51:12.357+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-16T01:51:12.359+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:51:12.475+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_history_table> on 2022-12-15 00:00:00+00:00
[2022-12-16T01:51:12.557+0000] {standard_task_runner.py:55} INFO - Started process 363 to run task
[2022-12-16T01:51:12.620+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_dag', 'create_history_table', 'scheduled__2022-12-15T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpa6adulke']
[2022-12-16T01:51:12.650+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask create_history_table
[2022-12-16T01:51:13.133+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_dag.create_history_table scheduled__2022-12-15T00:00:00+00:00 [running]> on host 158c8f40aaa8
[2022-12-16T01:51:13.644+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_dag
AIRFLOW_CTX_TASK_ID=create_history_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T00:00:00+00:00
[2022-12-16T01:51:13.659+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);
[2022-12-16T01:51:13.690+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-16T01:51:15.894+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-16T01:51:15.899+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS history (
    user_id INTEGER REFERENCES users (id),
    name TEXT,
    played_at TIMESTAMPTZ,
    album_name TEXT,
    artist_name TEXT
);, parameters: None
[2022-12-16T01:51:15.908+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "users" does not exist

[2022-12-16T01:51:15.915+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=daily_spotify_dag, task_id=create_history_table, execution_date=20221215T000000, start_date=20221216T015112, end_date=20221216T015115
[2022-12-16T01:51:15.930+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task create_history_table (relation "users" does not exist
; 363)
[2022-12-16T01:51:15.973+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T01:51:16.018+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
