[2022-12-14T12:50:32.846+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.create_wrapped_table manual__2022-12-14T12:50:30.483857+00:00 [queued]>
[2022-12-14T12:50:32.860+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.create_wrapped_table manual__2022-12-14T12:50:30.483857+00:00 [queued]>
[2022-12-14T12:50:32.861+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:50:32.861+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T12:50:32.862+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:50:32.873+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_wrapped_table> on 2022-12-14 12:50:30.483857+00:00
[2022-12-14T12:50:32.890+0000] {standard_task_runner.py:55} INFO - Started process 29402 to run task
[2022-12-14T12:50:32.901+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weekly_wrapped_dag', 'create_wrapped_table', 'manual__2022-12-14T12:50:30.483857+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/weekly_dag.py', '--cfg-path', '/tmp/tmp0fzpjexa']
[2022-12-14T12:50:32.902+0000] {standard_task_runner.py:83} INFO - Job 109: Subtask create_wrapped_table
[2022-12-14T12:50:32.985+0000] {task_command.py:389} INFO - Running <TaskInstance: weekly_wrapped_dag.create_wrapped_table manual__2022-12-14T12:50:30.483857+00:00 [running]> on host b92abc15fbab
[2022-12-14T12:50:33.041+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_wrapped_dag
AIRFLOW_CTX_TASK_ID=create_wrapped_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T12:50:30.483857+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T12:50:30.483857+00:00
[2022-12-14T12:50:33.045+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS weekly_wrapped (
    user_id INTEGER REFERENCES users (id),
    wrapped JSON,
    time_added DATE DEFAULT GETDATE()
);
[2022-12-14T12:50:33.057+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-14T12:50:33.208+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-14T12:50:33.211+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS weekly_wrapped (
    user_id INTEGER REFERENCES users (id),
    wrapped JSON,
    time_added DATE DEFAULT GETDATE()
);, parameters: None
[2022-12-14T12:50:33.229+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: function getdate() does not exist
LINE 4:     time_added DATE DEFAULT GETDATE()
                                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2022-12-14T12:50:33.237+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=weekly_wrapped_dag, task_id=create_wrapped_table, execution_date=20221214T125030, start_date=20221214T125032, end_date=20221214T125033
[2022-12-14T12:50:33.246+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 109 for task create_wrapped_table (function getdate() does not exist
LINE 4:     time_added DATE DEFAULT GETDATE()
                                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
; 29402)
[2022-12-14T12:50:33.281+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T12:50:33.305+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
