[2022-12-16T01:54:22.233+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:14.740520+00:00 [queued]>
[2022-12-16T01:54:22.242+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:14.740520+00:00 [queued]>
[2022-12-16T01:54:22.244+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:54:22.245+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-16T01:54:22.246+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:54:22.258+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2022-12-16 01:54:14.740520+00:00
[2022-12-16T01:54:22.269+0000] {standard_task_runner.py:55} INFO - Started process 597 to run task
[2022-12-16T01:54:22.273+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_dag', 'transform_task', 'manual__2022-12-16T01:54:14.740520+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmptq9s1xxp']
[2022-12-16T01:54:22.276+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask transform_task
[2022-12-16T01:54:22.331+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:14.740520+00:00 [running]> on host 158c8f40aaa8
[2022-12-16T01:54:22.381+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T01:54:14.740520+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T01:54:14.740520+00:00
[2022-12-16T01:54:22.389+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/songs.py", line 76, in transform_data
    for item in data:
TypeError: 'NoneType' object is not iterable
[2022-12-16T01:54:22.402+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=daily_spotify_dag, task_id=transform_task, execution_date=20221216T015414, start_date=20221216T015422, end_date=20221216T015422
[2022-12-16T01:54:22.410+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task transform_task ('NoneType' object is not iterable; 597)
[2022-12-16T01:54:22.445+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T01:54:22.464+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
